SELECT * FROM TABELA_DE_VENDEDORES

SELECT * FROM NOTAS_FISCAIS

-- Selecionar quantas notas fiscais de cada vendedor, exibindo nome
SELECT MATRICULA, COUNT(*) AS NUMEROS_NOTAS FROM NOTAS_FISCAIS
GROUP BY MATRICULA

SELECT NOTAS_FISCAIS.MATRICULA, TABELA_DE_VENDEDORES.NOME, COUNT(*) AS NUMEROS_NOTAS 
FROM NOTAS_FISCAIS
INNER JOIN TABELA_DE_VENDEDORES
ON NOTAS_FISCAIS.MATRICULA = TABELA_DE_VENDEDORES.MATRICULA
GROUP BY NOTAS_FISCAIS.MATRICULA, TABELA_DE_VENDEDORES.NOME

