SELECT * FROM TABELA_DE_CLIENTES;

SELECT NOME, CPF, BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;

--Alias

SELECT CPF AS IDENTIFICADOR, NOME AS [NOME DE CLIENTES], BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;

SELECT CPF AS IDENTIFICADOR, NOME AS [NOME DE CLIENTES], BAIRRO, CIDADE FROM TABELA_DE_CLIENTES TDC;

SELECT TDC.CPF, TDC.NOME, TDC.CIDADE FROM TABELA_DE_CLIENTES TDC;

SELECT TDC.* FROM TABELA_DE_CLIENTES TDC;

SELECT TABELA_DE_CLIENTES.CPF, TABELA_DE_CLIENTES.NOME FROM TABELA_DE_CLIENTES;