-- filtros quantitativos

SELECT * FROM TABELA_DE_CLIENTES
WHERE IDADE > 21;

SELECT * FROM TABELA_DE_CLIENTES
WHERE IDADE < 18;

SELECT * FROM TABELA_DE_CLIENTES
WHERE IDADE <= 20;

SELECT * FROM TABELA_DE_CLIENTES
WHERE IDADE <> 18;

-- data YYYY-MM-DD

SELECT * FROM TABELA_DE_CLIENTES
WHERE DATA_DE_NASCIMENTO >= '1995-11-14';

SELECT * FROM TABELA_DE_CLIENTES
WHERE DATA_DE_NASCIMENTO < '1995-11-14';

-- alfabeto

SELECT * FROM TABELA_DE_CLIENTES
WHERE BAIRRO >= 'Lapa';